kafka:
   image: spotify/kafka
   name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka


es:
   image: elasticsearch:2.0
   name: es
   ports:
      - "9200:9200"

models:
   image: tp33/django-docker:1.3
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - /home/johnson/Desktop/project4501_models/project4501_models:/app
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes project4501_models/wsgi.py" 

exp:
   image: tp33/django-docker:1.3
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   ports:
      - "8002:8000"
   volumes:
      - /home/johnson/Desktop/project4501_exp/project4501_exp:/app
   command: bash -c "pip install requests && mod_wsgi-express start-server --log-to-terminal --reload-on-changes project4501_exp/wsgi.py"

web:
   image: tp33/django-docker:1.3
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - /home/johnson/Desktop/project4501_web/project4501_web:/app
   command: bash -c "pip install requests  && chmod -R 755 /app/project4501_web/ && mod_wsgi-express start-server --working-directory /app --url-alias /static /app/project4501_web/static /app/project4501_web/wsgi.py --reload-on-changes"



batch:
   image: tp33/django-docker:1.3
   links:
      - kafka:kafka
      - es:es 
   ports:
      - "8003:8000"
   volumes:
      - /home/johnson/Desktop/project4501_batch/project4501_batch:/app
   command: bash -c "python searchIndexer.py && mod_wsgi-express start-server" 

# models:
#    image: tp33/django:1.2
#    external_links:
#       - mysql:db
#    ports:
#       - "8001:8000"
#    volumes:
#       - /home/user/Desktop/project4501_models-master:/app
#    command: bash -c "cd /app/project4501_models && python manage.py loaddata group3data.json && mod_wsgi-express start-server --working-directory /app/project4501_models --reload-on-changes /app/project4501_models/project4501_models/wsgi.py" 

# exp:
#    image: tp33/django:1.2
#    links:
#       - models:models-api
#    ports:
#       - "8002:8000"
#    volumes:
#       - /home/user/Desktop/project4501_exp-master:/app
#    command: bash -c "pip install requests && mod_wsgi-express start-server --working-directory /app/project4501_exp --reload-on-changes /app/project4501_exp/project4501_exp/wsgi.py"

# web:
#    image: tp33/django:1.2
#    links:
#       - exp:exp-api
#    ports:
#       - "8000:8000"
#    volumes:
#       - /home/user/Desktop/project4501_web-master:/app
#    command: bash -c "pip install requests  && chmod -R 755 /app/project4501_web/ && mod_wsgi-express start-server --working-directory /app --url-alias /static /app/project4501_web/static /app/project4501_web/wsgi.py --reload-on-changes"